%% This function is used to get the joints external torques, for the KUKA iiwa 7 R 800.

%% Syntax:
%  [ torques ] = getJointsExternalTorques( t )

%% ABout:
% This function is used to get the measured torques of the joints. Those
% torques are generated by an external force moment acting on the robot.
% The measurments are aquired from the torque sensors incorporated into the
% joints of the robot.

%% Arreguments:
% t: is the TCP/IP connection
% torques: the torques of the joints due to external force/moment, it is
% 1x7 cell array (unit Newton.Meter).

% Copy right, Mohammad SAFEEA, 11th of May 2017

